name: ci
permissions:
  contents: read
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  rst_check:
    name: rst format validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Install dependencies
        run: python -m pip install -U pip readme-renderer
      - name: rst validation
        run: |
          python -m readme_renderer -f rst README.rst -o /dev/null
          python -m readme_renderer -f rst CHANGES.rst -o /dev/null
  pytests:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t", "pypy-3.11"]
        exclude:
          - os: windows-latest
            python-version: "pypy-3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: python3 -m pip install --upgrade pip
      - run: pip install pytest pytest-asyncio
      - run: pip install --editable .
      - run: pytest
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.14'
        run: |
          pip install pytest-run-parallel
          pytest --iterations=4 --parallel-threads=auto
